import Head from 'next/head'
import { useState } from "react";

export default function Home() {
  const [message, setMessage] = useState<string>("");

  const click = async () => {
    const msg = await fetch("/api/liveness");
    const json = await msg.json()
    console.log(json);
    setMessage(json.text);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to baster starter project!
        </h1>
        <div>
          <button onClick={click} className="border-2">Call API</button>
        </div>
        <div>
          {message}
        </div>

      </main>

      <footer>
        Base by Seth Juarez
      </footer>
    </div>
  )
}
